//! Raises hip roofs over floor plans and writes them out as Wavefront OBJ.
//!
//! ```text
//! cargo run --example roof
//! cargo run --example roof -- --out my_dir --pitch 0.8
//! ```
//!
//! Open the `.obj` files in Blender, MeshLab, or any 3D viewer.
//!
//! The roof geometry itself lives in the library — see [`Roof`], which lifts a
//! skeleton into 3D. All this example adds is the OBJ serialisation, since
//! choosing a file format is the caller's business, not the crate's.

use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

use straight_skeleton::{skeleton, Point, Polygon, Roof};

/// How steep the roof is: rise over run. A pitch of 1.0 gives 45 degrees.
const DEFAULT_PITCH: f32 = 0.6;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let args: Vec<String> = std::env::args().collect();
    let mut out = PathBuf::from("target/roofs");
    if let Some(i) = args.iter().position(|a| a == "--out") {
        out = PathBuf::from(args.get(i + 1).ok_or("--out needs a directory")?);
    }
    let pitch: f32 = match args.iter().position(|a| a == "--pitch") {
        Some(i) => args.get(i + 1).ok_or("--pitch needs a number")?.parse()?,
        None => DEFAULT_PITCH,
    };
    fs::create_dir_all(&out)?;

    for (name, plan) in plans() {
        // Two lines, because the library does the work: the skeleton *is* the
        // roof, and `Roof` only has to read it off.
        let skel = skeleton(&plan)?;
        let roof = Roof::new(&skel, pitch)?;

        let path = out.join(format!("{name}.obj"));
        fs::write(&path, to_obj(&roof, name))?;
        println!(
            "{:<22} {:>2} panels, {:>2} vertices, ridge height {}",
            format!("{name}.obj"),
            roof.panels().len(),
            roof.verts().len(),
            roof.ridge_height(),
        );
    }

    println!("\nWrote OBJ files to {}", out.display());
    Ok(())
}

/// Serialises a roof to Wavefront OBJ.
///
/// Each panel becomes one face. OBJ handles n-gons, and a panel is flat by
/// construction, so no triangulation is needed.
fn to_obj(roof: &Roof, name: &str) -> String {
    let mut s = format!(
        "# {name} - hip roof generated by the straight-skeleton crate\n\
         # pitch {}; one face per wall, each a single flat panel\n\
         o {name}\n",
        roof.pitch(),
    );

    // Vertices are indexed by NodeId, so writing them in order means a panel's
    // corner ids are already the right OBJ indices (offset by one).
    for v in roof.verts() {
        let p = v.position;
        let _ = writeln!(s, "v {} {} {}", p.x, p.y, p.z);
    }

    for panel in roof.panels() {
        // Name each group after the wall it rises from — the provenance the
        // skeleton hands over for free.
        let _ = writeln!(s, "g wall_{}", panel.wall.0);
        let corners = panel
            .corners
            .iter()
            .map(|n| (n.0 + 1).to_string()) // OBJ indices are 1-based
            .collect::<Vec<_>>()
            .join(" ");
        let _ = writeln!(s, "f {corners}");
    }
    s
}

/// Floor plans to roof.
fn plans() -> Vec<(&'static str, Polygon)> {
    vec![
        (
            "simple-hip",
            Polygon::from_outer(&[
                Point::new(0, 0),
                Point::new(120, 0),
                Point::new(120, 80),
                Point::new(0, 80),
            ])
            .unwrap(),
        ),
        (
            "pyramid",
            Polygon::from_outer(&[
                Point::new(0, 0),
                Point::new(80, 0),
                Point::new(80, 80),
                Point::new(0, 80),
            ])
            .unwrap(),
        ),
        (
            "l-shaped-house",
            Polygon::from_outer(&[
                Point::new(0, 0),
                Point::new(160, 0),
                Point::new(160, 70),
                Point::new(70, 70),
                Point::new(70, 150),
                Point::new(0, 150),
            ])
            .unwrap(),
        ),
        (
            "t-shaped-house",
            Polygon::from_outer(&[
                Point::new(0, 0),
                Point::new(180, 0),
                Point::new(180, 60),
                Point::new(120, 60),
                Point::new(120, 140),
                Point::new(60, 140),
                Point::new(60, 60),
                Point::new(0, 60),
            ])
            .unwrap(),
        ),
        (
            "courtyard",
            Polygon::new(
                &[
                    Point::new(0, 0),
                    Point::new(200, 0),
                    Point::new(200, 160),
                    Point::new(0, 160),
                ],
                &[vec![
                    Point::new(70, 55),
                    Point::new(130, 55),
                    Point::new(130, 105),
                    Point::new(70, 105),
                ]],
            )
            .unwrap(),
        ),
    ]
}
